import { Iproduct } from './iproduct'



export let listOfp: Iproduct[] = [
    { ID: 1, Name: "t-shirt", price: 5000, quantity: 5 }
    , { ID: 2, Name: "pantalon", price: 5000, quantity: 3 }
    , { ID: 3, Name: "blouse", price: 5000, quantity: 7 }
    , { ID: 4, Name: "skirt", price: 5000, quantity: 8 }
    , { ID: 5, Name: "skirt", price: 5000, quantity: 1 }
    , { ID: 6, Name: "skirt", price: 5000, quantity: 0 }
];
